"""removed testing column to tracks

Revision ID: e0d610d30201
Revises: 71c51601b989
Create Date: 2025-05-28 21:36:49.920817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d610d30201'
down_revision: Union[str, None] = '71c51601b989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('testing', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
